### ISSUE TITLE
thirdpartyemailpassword addition

### ISSUE THREAD

**Issue by kubeworkz** [ITenthusiasm/remix-supertokens#4]
I'm want to add the `thirdpartyemailpassword` recipe. Where's a good place to start? Cheers, Dave

**Comment by ITenthusiasm** [comment]
Hey @kubeworkz. Appreciate your eagerness to contribute!

When I first wrote the code for this repo, I didn't have the idea of exemplifying multiple recipes in mind. (I also didn't expect contributors. :sweat_smile:) So I think we'll need to figure out the best way to organize this repository to handle different examples before adding too many.

If we're going to prepare for this, there's also some general cleaning up to do. I need to update some TS types (the app itself still runs fine). I'd also probably need to pull all of the `react-hook-form` stuff into its own "example section". Same with the `useFormLocalStorage` logic. This will help minimize any confusion or distractions for people trying to get the basic setup up and running.

---

After the repo is reorganized to handle different examples, we could just add an "example section" for ThirdPartyEmailPassword. I'm assuming most of the code would look the same as the regular `EmailPassword` recipe. Most of the changes would probably be in `server.js`. We should, of course, exclude `react-hook-form` (and similar unnecessary logic) from any new recipes in order to keep things simple for readers.

**Comment by kubeworkz** [comment]
Thanks for the input. Sounds like a solid initial approach. I'll do some noodling on this.

**Comment by kubeworkz** [comment]
Here's an attempt I made by generating a project from `supertokens-auth-react` example: `thirdpartyemailpassword => backend node / frontend react` and converting the frontend to Remix. 

It has an issue running: `{getSuperTokensRoutesForReactRouterDom(require("react-router-dom"))}` in the `root.tsx` file. I don't think `Supertokens.init` is getting initialized.
[new-app.tar.gz](https://github.com/ITenthusiasm/remix-supertokens/files/9718679/new-app.tar.gz)

**Comment by ITenthusiasm** [comment]
Thanks for putting progress towards this! Sorry for these late responses. Life is a bit busy on my end between work and church life. But as I get opportunity, I'll try to stay in contact. (I'll at least try not to let a week go by at a time. :grimacing:)

Are you able to display these examples through some kind of PR or `Fork`? I think that would make review a little easier/faster since there wouldn't be a need to download and unzip a file. (Plus it would have more immediate visibility for others.) If you need any help with that, feel free to let me know.

Since we're using Remix, I actually think we should be able to avoid using `supertokens-auth-react`, `supertokens-website`, and the like. We should only need the backend in order to perform authentication/authorization. Were you able to see that functionality from the existing example in this codebase? (I hope so; if not, then I've broken something :sweat_smile:)

**Comment by ITenthusiasm** [comment]
@kubeworkz Now that `ThirdParty` is supported in this project, I think this issue can be marked as complete. Hopefully the work done here benefits many developers. 🙏🏾
